"""added domain table, new fks, new fields

Revision ID: 147eb783a7a4
Revises: 43ab1936b8b0
Create Date: 2013-11-05 16:15:22.536433

"""

# revision identifiers, used by Alembic.
revision = '147eb783a7a4'
down_revision = '43ab1936b8b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'campaign', sa.Column('count_engagements', sa.Integer(), nullable=True))
    op.add_column(u'campaign', sa.Column('count_uniques', sa.Integer(), nullable=True))
    op.add_column(u'campaign_target', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column(u'commercial', sa.Column('quota_uniques', sa.Integer(), nullable=True))
    op.add_column(u'commercial', sa.Column('quota_engagements', sa.Integer(), nullable=True))
    op.add_column(u'prize', sa.Column('domain_id', sa.Integer(), nullable=False))
    op.add_column(u'unlock', sa.Column('sitting_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'unlock', 'sitting_id')
    op.drop_column(u'prize', 'domain_id')
    op.drop_column(u'commercial', 'quota_engagements')
    op.drop_column(u'commercial', 'quota_uniques')
    op.drop_column(u'campaign_target', 'campaign_id')
    op.drop_column(u'campaign', 'count_uniques')
    op.drop_column(u'campaign', 'count_engagements')
    op.drop_table('domain')
    ### end Alembic commands ###
