"""empty message

Revision ID: 21379e53cadd
Revises: 4524e857fe4d
Create Date: 2013-05-11 20:23:10.608584

"""

# revision identifiers, used by Alembic.
revision = '21379e53cadd'
down_revision = '4524e857fe4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameplay', sa.Column('actions', sa.Integer(), nullable=True))
    op.add_column('gameplay', sa.Column('timer', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameplay', 'timer')
    op.drop_column('gameplay', 'actions')
    ### end Alembic commands ###
