"""empty message

Revision ID: 2336576ae7ef
Revises: 4d7be66401af
Create Date: 2013-05-15 00:00:57.338593

"""

# revision identifiers, used by Alembic.
revision = '2336576ae7ef'
down_revision = '4d7be66401af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_users', sa.Column('hashed_email', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_users', 'hashed_email')
    ### end Alembic commands ###
