"""set nullable sitting_id campaign_target

Revision ID: 2566cded273c
Revises: 147eb783a7a4
Create Date: 2013-11-05 16:53:43.757833

"""

# revision identifiers, used by Alembic.
revision = '2566cded273c'
down_revision = '147eb783a7a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_target', u'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unlock', u'sitting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.execute('update campaign_target set campaign_id=1 where campaign_id isnull')
    op.execute('update unlock set sitting_id=1 where sitting_id isnull')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unlock', u'sitting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaign_target', u'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
