"""empty message

Revision ID: 33a11e4c3a5a
Revises: 406ec2d83a59
Create Date: 2013-08-08 19:52:50.590598

"""

# revision identifiers, used by Alembic.
revision = '33a11e4c3a5a'
down_revision = '406ec2d83a59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('game', sa.Column('play_order', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('game', 'play_order')
    ### end Alembic commands ###
    pass
