"""changed order to be small integer

Revision ID: 383dad2fe187
Revises: 2a59d89955a1
Create Date: 2013-08-08 14:50:30.214679

"""

# revision identifiers, used by Alembic.
revision = '383dad2fe187'
down_revision = '2a59d89955a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
