"""empty message

Revision ID: 38954fa31c76
Revises: bea569d54f5
Create Date: 2013-05-14 15:53:52.386143

"""

# revision identifiers, used by Alembic.
revision = '38954fa31c76'
down_revision = 'bea569d54f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.drop_column('game', 'order')
    ### end Alembic commands ###
