"""empty message

Revision ID: 3c2f4986a7ee
Revises: 380d67b6fa20
Create Date: 2013-10-31 01:08:47.359343

"""

# revision identifiers, used by Alembic.
revision = '3c2f4986a7ee'
down_revision = '380d67b6fa20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('industry', sa.String(length=30), nullable=True))
    op.add_column('campaign_target', sa.Column('age', sa.String(length=5), nullable=True))
    op.add_column('campaign_target', sa.Column('household_income', sa.String(length=22), nullable=True))
    op.add_column('campaign_target', sa.Column('pets', sa.Boolean(), nullable=True))
    op.drop_column('campaign_target', u'max_age')
    op.drop_column('campaign_target', u'min_household_income')
    op.drop_column('campaign_target', u'max_household_income')
    op.drop_column('campaign_target', u'min_age')
    op.add_column('rapleaf', sa.Column('pets', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapleaf', 'pets')
    op.add_column('campaign_target', sa.Column(u'min_age', sa.VARCHAR(length=5), nullable=True))
    op.add_column('campaign_target', sa.Column(u'max_household_income', sa.VARCHAR(length=22), nullable=True))
    op.add_column('campaign_target', sa.Column(u'min_household_income', sa.VARCHAR(length=22), nullable=True))
    op.add_column('campaign_target', sa.Column(u'max_age', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('campaign_target', 'pets')
    op.drop_column('campaign_target', 'household_income')
    op.drop_column('campaign_target', 'age')
    op.drop_column('campaign', 'industry')
    ### end Alembic commands ###
