"""no play order

Revision ID: 406ec2d83a59
Revises: f7ca5b8b051
Create Date: 2013-08-08 17:49:53.509585

"""

# revision identifiers, used by Alembic.
revision = '406ec2d83a59'
down_revision = 'f7ca5b8b051'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
