"""empty message

Revision ID: 42a6d2b5f1d1
Revises: 4a39224849de
Create Date: 2013-04-23 14:13:01.805943

"""

# revision identifiers, used by Alembic.
revision = '42a6d2b5f1d1'
down_revision = '4a39224849de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial', sa.Column('name', sa.String(length=256), nullable=False, server_default=""))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commercial', 'name')
    ### end Alembic commands ###
