"""empty message

Revision ID: 43ab1936b8b0
Revises: 3c2f4986a7ee
Create Date: 2013-11-01 16:21:47.440009

"""

# revision identifiers, used by Alembic.
revision = '43ab1936b8b0'
down_revision = '3c2f4986a7ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('taken_survey', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'taken_survey')
    ### end Alembic commands ###
