"""empty message

Revision ID: 43d99ea4984a
Revises: 33a11e4c3a5a
Create Date: 2013-10-11 16:47:12.958730

"""

# revision identifiers, used by Alembic.
revision = '43d99ea4984a'
down_revision = '33a11e4c3a5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropblocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dropblocks')
    ### end Alembic commands ###
