"""empty message

Revision ID: 4524e857fe4d
Revises: 9c25142801c
Create Date: 2013-05-04 23:47:53.493658

"""

# revision identifiers, used by Alembic.
revision = '4524e857fe4d'
down_revision = '9c25142801c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('active', sa.Boolean(), server_default="false"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'active')
    ### end Alembic commands ###
