"""empty message

Revision ID: 496f9c72aab5
Revises: 21379e53cadd
Create Date: 2013-05-13 00:35:25.825790

"""

# revision identifiers, used by Alembic.
revision = '496f9c72aab5'
down_revision = '21379e53cadd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sitting_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('event_data', postgresql.HSTORE(), nullable=True),
    sa.ForeignKeyConstraint(['sitting_id'], ['sitting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytic_events')
    ### end Alembic commands ###
