"""empty message

Revision ID: 4a39224849de
Revises: None
Create Date: 2013-04-18 00:03:45.076356

"""

# revision identifiers, used by Alembic.
revision = '4a39224849de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
