"""empty message

Revision ID: 4d7be66401af
Revises: 38954fa31c76
Create Date: 2013-05-14 22:53:23.381619

"""

# revision identifiers, used by Alembic.
revision = '4d7be66401af'
down_revision = '38954fa31c76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameplay', sa.Column('user_id', sa.Integer(), nullable=False, server_default="1"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameplay', 'user_id')
    ### end Alembic commands ###
