"""empty message

Revision ID: 508fb3a45a86
Revises: 55cc90d76868
Create Date: 2013-07-26 12:35:05.084728

"""

# revision identifiers, used by Alembic.
revision = '508fb3a45a86'
down_revision = '55cc90d76868'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sitting', u'time_start',  name='get_inventory')
    op.alter_column('sitting', u'time_end',    name='modal_award')
    op.add_column('sitting', sa.Column('modal_open', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sitting', 'get_inventory', new_column_name=u'time_start')
    op.alter_column('sitting', 'modal_award', new_column_name=u'time_end')
    op.drop_column('sitting', 'modal_open')

    ### end Alembic commands ###
