"""empty message

Revision ID: 55cc90d76868
Revises: 9ba45accd45
Create Date: 2013-05-24 18:26:03.038983

"""

# revision identifiers, used by Alembic.
revision = '55cc90d76868'
down_revision = '9ba45accd45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_users', sa.Column('foreign_id', sa.String(length=80), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foreign_users', 'foreign_id')
    ### end Alembic commands ###
