"""false null sitting_id campaign_id

Revision ID: 6b87ee0fca
Revises: 2566cded273c
Create Date: 2013-11-05 17:49:14.873530

"""

# revision identifiers, used by Alembic.
revision = '6b87ee0fca'
down_revision = '2566cded273c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_target', u'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unlock', u'sitting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unlock', u'sitting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaign_target', u'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
