"""empty message

Revision ID: 9ba45accd45
Revises: 2336576ae7ef
Create Date: 2013-05-21 01:33:13.787576

"""

# revision identifiers, used by Alembic.
revision = '9ba45accd45'
down_revision = '2336576ae7ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameplay', u'time_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('gameplay', u'time_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameplay', u'time_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('gameplay', u'time_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
