"""empty message

Revision ID: 9c25142801c
Revises: 5346e6152e6b
Create Date: 2013-04-30 18:40:46.955747

"""

# revision identifiers, used by Alembic.
revision = '9c25142801c'
down_revision = '5346e6152e6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', u'commercial_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', u'commercial_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
