"""empty message

Revision ID: bea569d54f5
Revises: 496f9c72aab5
Create Date: 2013-05-13 01:05:29.779753

"""

# revision identifiers, used by Alembic.
revision = 'bea569d54f5'
down_revision = '496f9c72aab5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapleaf',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=5), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('household_income', sa.String(length=22), nullable=True),
    sa.Column('marital_status', sa.String(length=7), nullable=True),
    sa.Column('children', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapleaf')
    ### end Alembic commands ###
