"""no nulls in order

Revision ID: f7ca5b8b051
Revises: 383dad2fe187
Create Date: 2013-08-08 14:58:42.118194

"""

# revision identifiers, used by Alembic.
revision = 'f7ca5b8b051'
down_revision = '383dad2fe187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
